// src/components/Card.vue
<template>
  <div className="cms-vue-boilerplate-card">
    <p>
      {{ reasonsText }}
    </p>
    <button className="btn" v-on:click="increaseClickCount">
      Click me!
    </button>
  </div>
</template>

<script>
const pluralize = (n, noun, suffix) => `${n !== 1 ? 'are' : 'is'} ${n} ${noun + (n !== 1 ? suffix : '')}`;

export default {
  name: 'Card',
  props: ['initialClickCount'],
  data: function() {
    return {
      reasonsCount: this.initialClickCount,
    };
  },
  computed: {
    reasonsText() {
      return `There are ${
        this.reasonsCount > 0
          ? pluralize(this.reasonsCount, 'reason', 's')
          : 'so many reasons'
      } to use HubSpot CMS + Vue!`
    }
  },
  methods: {
    increaseClickCount() {
      this.reasonsCount += 1;
    },
  },
};
</script>

// src/components/Card.svelte
<script>
  import './Card.scss';

  let count = 0;

  const increment = () => {
    count++;
  };
</script>

<div class="cms-svelte-boilerplate__card">
  {#if count === 0}
    <p>There are so many reasons to use HubSpot CMS + Svelte!</p>
  {:else if count === 1}
    <p>There is 1 reason to use HubSpot CMS + Svelte!</p>
  {:else}
    <p>{`There are ${count} reasons to use HubSpot CMS + Svelte!`}</p>
  {/if}
  <button class="btn" on:click={increment}>Click me!</button>
</div>
