// src/App.vue
<template>
  <!-- <div className="cms-react-boilerplate__container">
    <div className="spinning-logo__container">
      <SpinningLogo :src="vueLogo" alt="Vue logo" />
      <SpinningLogo :src="sprocketLogo" alt="sprocket logo" isSprocket="true" />
    </div>
    <p>Edit <code>src/App.js</code> and save to reload.</p>
    <Card :initialClickCount="moduleData.initial_count" />
  </div> -->
  <div id="app">
    <!-- <img alt="Vue logo" :src="vueLogo" /> -->
    <HelloWorld msg="Welcome to HubVue" />
    Hello World
  </div>
</template>

<script>
// import Card from '@/components/Card.vue';
import HelloWorld from '@/components/HelloWorld.vue';
// import SpinningLogo from '@/components/SpinningLogo.vue';
// import sprocketLogo from '@/assets/sprocket.svg';
// import vueLogo from '@/assets/logo.svg';

export default {
  name: 'App',
  props: ['moduleData'],
  // data: function() {
  //   return {
  //     sprocketLogo,
  //     vueLogo,
  //   };
  // },
  created: function() {
    // eslint-disable-next-line no-console
    console.log(
      'all of your data typically accessed via the "module" keyword in HubL is available as JSON here!',
      this.moduleData,
    );
  },
  components: {
    // Card,
    HelloWorld,
    // SpinningLogo,
  },
};
</script>

<style lang="scss">
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
</style>

// src/App.svelte
<script>
  export let name;
  import svelteLogo from './assets/svelte.svg';
  import sprocketLogo from './assets/sprocket.svg';
  import Card from './components/Card.svelte';
</script>

<style>
  h1 {
    color: purple;
  }
</style>

<div class="cms-svelte-boilerplate">
  <div class="cms-svelte-boilerplate__container">
    <h1>Hello {name}!</h1>
    <div class="spinning-logo__container">
      <img class="spinning-logo" src={svelteLogo} alt="svelte logo" />
      <img
        class="spinning-logo spinning-logo--sprocket"
        src={sprocketLogo}
        alt="sprocket logo" />
    </div>
    <p>
      Edit
      <code>src/App.js</code>
      and save to reload.
    </p>
    <Card />
  </div>
</div>
